extent.reporter.spark.start=true
extent.reporter.spark.out=SparkReport/Customer_360_SparkReport.html
extent.reporter.spark.config=src/main/resources/extent-config.xml

screenshot.dir=Screenshot
screenshot.rel.path=../Screenshot/

extent.reporter.pdf.start=false
extent.reporter.pdf.out=PdfReport/Customer_360_PdfReport.pdf

basefolder.name=Test Results/Customer_360 Reports
basefolder.datetimepattern=d-MMM-YY-HH-mm-ss
#extent.reporter.spark.base64imagesrc=true